<?php

namespace Database\Seeders;

use App\Models\User;
// use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class DatabaseSeeder extends Seeder
{
    /**
     * Seed the application's database.
     */
    public function run()
    {
        

        // Seed ranks table
        DB::table('ranks')->insert([
            [
                'id' => 1,
                'icon' => 'uploads/Rank_Icon/bronze.png',
                'rank' => 'Beginner',
                'order' => 1,
                'req_xp' => 0,
                'created_at' => '2025-05-16 07:32:36',
                'updated_at' => '2025-05-16 07:32:36',
            ],
            [
                'id' => 2,
                'icon' => 'uploads/Rank_Icon/1747552957.png',
                'rank' => 'Intermediate',
                'order' => 2,
                'req_xp' => 25,
                'created_at' => '2025-05-17 01:55:44',
                'updated_at' => '2025-05-18 01:37:37',
            ],
            [
                'id' => 3,
                'icon' => 'Uploads/Rank_Icon/1747552965.png',
                'rank' => 'Advance',
                'order' => 3,
                'req_xp' => 75,
                'created_at' => '2025-05-17 01:57:32',
                'updated_at' => '2025-05-18 01:37:45',
            ],
            [
                'id' => 4,
                'icon' => 'Uploads/Rank_Icon/1747552972.png',
                'rank' => 'Expert',
                'order' => 4,
                'req_xp' => 150,
                'created_at' => '2025-05-17 01:58:33',
                'updated_at' => '2025-05-18 01:37:52',
            ],
            [
                'id' => 5,
                'icon' => 'Uploads/Rank_Icon/1747553041.png',
                'rank' => 'Master',
                'order' => 5,
                'req_xp' => 300,
                'created_at' => '2025-05-17 02:00:21',
                'updated_at' => '2025-05-18 01:39:01',
            ],
        ]);

        // Seed modules table
        DB::table('modules')->insert([
            [
                'id' => 1,
                'name' => 'Python',
                'icon' => 'Uploads/Module_Icon/1747586026.png',
                'created_at' => '2025-05-16 22:29:29',
                'updated_at' => '2025-05-18 10:48:46',
            ],
            [
                'id' => 2,
                'name' => 'JavaScript',
                'icon' => 'Uploads/Module_Icon/1747455582.png',
                'created_at' => '2025-05-16 22:34:42',
                'updated_at' => '2025-05-16 22:34:42',
            ],
            [
                'id' => 3,
                'name' => 'HTML',
                'icon' => 'Uploads/Module_Icon/1747455664.png',
                'created_at' => '2025-05-16 22:36:04',
                'updated_at' => '2025-05-16 22:36:04',
            ],
            [
                'id' => 4,
                'name' => 'CSS',
                'icon' => 'Uploads/Module_Icon/1747455735.png',
                'created_at' => '2025-05-16 22:37:15',
                'updated_at' => '2025-05-16 22:37:15',
            ],
            [
                'id' => 5,
                'name' => 'PHP',
                'icon' => 'Uploads/Module_Icon/1747456219.png',
                'created_at' => '2025-05-16 22:45:19',
                'updated_at' => '2025-05-16 22:45:19',
            ],
            [
                'id' => 6,
                'name' => 'HTTP',
                'icon' => 'Uploads/Module_Icon/1747465824.png',
                'created_at' => '2025-05-17 01:25:24',
                'updated_at' => '2025-05-17 01:25:24',
            ],
        ]);

        // Seed achievements table
        DB::table('achievements')->insert([
            [
                'id' => 1,
                'title' => 'HTML Hero',
                'description' => 'Complete all courses in HTML Module',
                'type' => 'Module Completed',
                'criteria_module' => 3,
                'criteria_amount' => 0,
                'xp_reward' => 25,
                'icon' => 'Uploads/Achievement_Icon/1747468116.png',
                'created_at' => '2025-05-17 02:03:36',
                'updated_at' => '2025-05-18 10:45:28',
            ],
            [
                'id' => 2,
                'title' => 'Time Novice',
                'description' => 'Spent 10 min on any module',
                'type' => 'Time Spent',
                'criteria_module' => null,
                'criteria_amount' => 600,
                'xp_reward' => 5,
                'icon' => 'Uploads/Achievement_Icon/1747552805.png',
                'created_at' => '2025-05-17 02:07:01',
                'updated_at' => '2025-05-18 01:36:46',
            ],
            [
                'id' => 4,
                'title' => 'CSS Hero',
                'description' => 'Complete all courses in CSS Module',
                'type' => 'Module Completed',
                'criteria_module' => 4,
                'criteria_amount' => 0,
                'xp_reward' => 25,
                'icon' => 'Uploads/Achievement_Icon/1747468442.png',
                'created_at' => '2025-05-17 02:09:02',
                'updated_at' => '2025-05-18 10:45:40',
            ],
            [
                'id' => 5,
                'title' => 'TIme Master',
                'description' => 'spend 3 hours on any module',
                'type' => 'Time Spent',
                'criteria_module' => null,
                'criteria_amount' => 10800,
                'xp_reward' => 80,
                'icon' => 'Uploads/Achievement_Icon/1747552886.png',
                'created_at' => '2025-05-17 02:13:07',
                'updated_at' => '2025-05-18 01:37:02',
            ],
            [
                'id' => 6,
                'title' => 'JS completed',
                'description' => 'Complete all courses in JavaScript Module',
                'type' => 'Module Completed',
                'criteria_module' => 2,
                'criteria_amount' => 0,
                'xp_reward' => 25,
                'icon' => 'Uploads/Achievement_Icon/1747469091.png',
                'created_at' => '2025-05-17 02:19:51',
                'updated_at' => '2025-05-18 10:47:15',
            ],
            [
                'id' => 7,
                'title' => 'Python Tamer',
                'description' => 'Complete all courses in Python Module',
                'type' => 'Module Completed',
                'criteria_module' => 1,
                'criteria_amount' => 0,
                'xp_reward' => 15,
                'icon' => 'Uploads/Achievement_Icon/1747585793.png',
                'created_at' => '2025-05-18 10:44:53',
                'updated_at' => '2025-05-18 10:44:53',
            ],
        ]);

        // Seed courses table
        DB::table('courses')->insert([
            [
                'id' => 1,
                'module_id' => 1,
                'title' => 'Installing Python Modules',
                'description' => 'safdsaf',
                'source' => 'Python Docs',
                'type' => 'Documentation',
                'difficulty_level' => 'Beginner',
                'url' => 'https://docs.python.org/3/installing/index.html',
                'order' => 1,
                'created_at' => '2025-05-16 22:31:00',
                'updated_at' => '2025-05-16 22:31:35',
            ],
            [
                'id' => 2,
                'module_id' => 2,
                'title' => 'JavaScript',
                'description' => 'JS courses',
                'source' => 'MDN Web Docs',
                'type' => 'Documentation',
                'difficulty_level' => 'Beginner',
                'url' => 'https://developer.mozilla.org/en-US/docs/Web/JavaScript',
                'order' => 1,
                'created_at' => '2025-05-16 22:38:35',
                'updated_at' => '2025-05-16 22:38:35',
            ],
            [
                'id' => 3,
                'module_id' => 3,
                'title' => 'HTML: HyperText Markup Language',
                'description' => 'HTML courses',
                'source' => 'MDN Web Docs',
                'type' => 'Documentation',
                'difficulty_level' => 'Beginner',
                'url' => 'https://developer.mozilla.org/en-US/docs/Web/HTML',
                'order' => 1,
                'created_at' => '2025-05-16 22:40:19',
                'updated_at' => '2025-05-16 22:40:19',
            ],
            [
                'id' => 4,
                'module_id' => 4,
                'title' => 'CSS: Cascading Style Sheets',
                'description' => 'CSS courses',
                'source' => 'MDN Web Docs',
                'type' => 'Documentation',
                'difficulty_level' => 'Beginner',
                'url' => 'https://developer.mozilla.org/en-US/docs/Web/CSS',
                'order' => 1,
                'created_at' => '2025-05-16 22:41:41',
                'updated_at' => '2025-05-16 22:41:41',
            ],
            [
                'id' => 5,
                'module_id' => 3,
                'title' => 'Guides',
                'description' => 'sadsadas',
                'source' => 'MDN Web Docs',
                'type' => 'Documentation',
                'difficulty_level' => 'Beginner',
                'url' => 'https://developer.mozilla.org/en-US/docs/Web/HTML/Guides',
                'order' => 2,
                'created_at' => '2025-05-16 22:49:08',
                'updated_at' => '2025-05-16 22:49:36',
            ],
            [
                'id' => 6,
                'module_id' => 3,
                'title' => 'Content categories',
                'description' => 'Content categories',
                'source' => 'MDN Web Docs',
                'type' => 'Documentation',
                'difficulty_level' => 'Beginner',
                'url' => 'https://developer.mozilla.org/en-US/docs/Web/HTML/Guides/Content_categories',
                'order' => 3,
                'created_at' => '2025-05-16 22:50:41',
                'updated_at' => '2025-05-16 22:50:41',
            ],
            [
                'id' => 7,
                'module_id' => 3,
                'title' => 'HTML comments',
                'description' => 'Using HTML comments <!-- … -->',
                'source' => 'MDN Web Docs',
                'type' => 'Documentation',
                'difficulty_level' => 'Beginner',
                'url' => 'https://developer.mozilla.org/en-US/docs/Web/HTML/Guides/Comments',
                'order' => 4,
                'created_at' => '2025-05-16 22:51:29',
                'updated_at' => '2025-05-17 01:28:36',
            ],
            [
                'id' => 8,
                'module_id' => 3,
                'title' => 'Date and time formats',
                'description' => 'Using date and time formats in HTML',
                'source' => 'MDN Web Docs',
                'type' => 'Documentation',
                'difficulty_level' => 'Beginner',
                'url' => 'https://developer.mozilla.org/en-US/docs/Web/HTML/Guides/Date_and_time_formats',
                'order' => 5,
                'created_at' => '2025-05-16 22:53:14',
                'updated_at' => '2025-05-17 01:29:06',
            ],
            [
                'id' => 9,
                'module_id' => 3,
                'title' => 'Constraint Validation',
                'description' => 'Using HTML form validation and the Constraint Validation API',
                'source' => 'MDN Web Docs',
                'type' => 'Documentation',
                'difficulty_level' => 'Beginner',
                'url' => 'https://developer.mozilla.org/en-US/docs/Web/HTML/Guides/Constraint_validation',
                'order' => 6,
                'created_at' => '2025-05-17 01:28:05',
                'updated_at' => '2025-05-17 01:28:05',
            ],
            [
                'id' => 10,
                'module_id' => 4,
                'title' => 'CSS styling basics',
                'description' => 'CSS styling basics',
                'source' => 'MDN Web Docs',
                'type' => 'Documentation',
                'difficulty_level' => 'Beginner',
                'url' => 'https://developer.mozilla.org/en-US/docs/Learn_web_development/Core/Styling_basics',
                'order' => 2,
                'created_at' => '2025-05-17 01:30:23',
                'updated_at' => '2025-05-17 01:30:23',
            ],
            [
                'id' => 11,
                'module_id' => 4,
                'title' => 'Basic CSS selectors',
                'description' => 'Basic CSS selectors',
                'source' => 'MDN Web Docs',
                'type' => 'Documentation',
                'difficulty_level' => 'Beginner',
                'url' => 'https://developer.mozilla.org/en-US/docs/Learn_web_development/Core/Styling_basics/Basic_selectors',
                'order' => 3,
                'created_at' => '2025-05-17 01:31:23',
                'updated_at' => '2025-05-17 01:31:23',
            ],
            [
                'id' => 12,
                'module_id' => 4,
                'title' => 'CSS values and units',
                'description' => 'CSS values and units',
                'source' => 'MDN Web Docs',
                'type' => 'Documentation',
                'difficulty_level' => 'Beginner',
                'url' => 'https://developer.mozilla.org/en-US/docs/Learn_web_development/Core/Styling_basics/Values_and_units',
                'order' => 4,
                'created_at' => '2025-05-17 01:33:51',
                'updated_at' => '2025-05-17 01:33:51',
            ],
            [
                'id' => 13,
                'module_id' => 4,
                'title' => 'CSS text styling',
                'description' => 'CSS text styling',
                'source' => 'MDN Web Docs',
                'type' => 'Documentation',
                'difficulty_level' => 'Beginner',
                'url' => 'https://developer.mozilla.org/en-US/docs/Learn_web_development/Core/Text_styling',
                'order' => 5,
                'created_at' => '2025-05-17 01:35:41',
                'updated_at' => '2025-05-17 01:35:41',
            ],
            [
                'id' => 14,
                'module_id' => 4,
                'title' => 'CSS layout',
                'description' => 'CSS layout',
                'source' => 'MDN Web Docs',
                'type' => 'Documentation',
                'difficulty_level' => 'Beginner',
                'url' => 'https://developer.mozilla.org/en-US/docs/Learn_web_development/Core/CSS_layout',
                'order' => 6,
                'created_at' => '2025-05-17 01:36:26',
                'updated_at' => '2025-05-17 01:36:26',
            ],
            [
                'id' => 15,
                'module_id' => 2,
                'title' => 'JavaScript Guide',
                'description' => 'JavaScript Guide',
                'source' => 'MDN Web Docs',
                'type' => 'Documentation',
                'difficulty_level' => 'Beginner',
                'url' => 'https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Grammar_and_types',
                'order' => 2,
                'created_at' => '2025-05-17 01:39:32',
                'updated_at' => '2025-05-17 01:39:32',
            ],
            [
                'id' => 16,
                'module_id' => 2,
                'title' => 'Advanced JavaScript objects',
                'description' => 'Advanced JavaScript objects',
                'source' => 'MDN Web Docs',
                'type' => 'Documentation',
                'difficulty_level' => 'Beginner',
                'url' => 'https://developer.mozilla.org/en-US/docs/Learn_web_development/Extensions/Advanced_JavaScript_objects',
                'order' => 3,
                'created_at' => '2025-05-17 01:40:22',
                'updated_at' => '2025-05-17 01:40:22',
            ],
            [
                'id' => 17,
                'module_id' => 2,
                'title' => 'Inheritance and the prototype chain',
                'description' => 'Inheritance and the prototype chain',
                'source' => 'MDN Web Docs',
                'type' => 'Documentation',
                'difficulty_level' => 'Beginner',
                'url' => 'https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Inheritance_and_the_prototype_chain',
                'order' => 0,
                'created_at' => '2025-05-17 01:42:36',
                'updated_at' => '2025-05-17 01:42:36',
            ],
            [
                'id' => 18,
                'module_id' => 2,
                'title' => 'AggregateError',
                'description' => 'AggregateError: No Promise in Promise.any was resolved',
                'source' => 'MDN Web Docs',
                'type' => 'Documentation',
                'difficulty_level' => 'Beginner',
                'url' => 'https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Errors/Promise_any_all_rejected',
                'order' => 5,
                'created_at' => '2025-05-17 01:44:49',
                'updated_at' => '2025-05-17 01:44:49',
            ],
            [
                'id' => 19,
                'module_id' => 6,
                'title' => 'Hypertext Transfer Protocol (HTTP)',
                'description' => 'Hypertext Transfer Protocol (HTTP)',
                'source' => 'MDN Web Docs',
                'type' => 'Documentation',
                'difficulty_level' => 'Beginner',
                'url' => 'https://developer.mozilla.org/en-US/docs/Web/HTTP',
                'order' => 1,
                'created_at' => '2025-05-17 01:49:28',
                'updated_at' => '2025-05-17 01:49:28',
            ],
            [
                'id' => 20,
                'module_id' => 1,
                'title' => 'Introduction',
                'description' => 'Introduction to Python Library',
                'source' => 'Python Docs',
                'type' => 'Documentation',
                'difficulty_level' => 'Beginner',
                'url' => 'https://docs.python.org/3/library/intro.html',
                'order' => 2,
                'created_at' => '2025-05-18 10:41:55',
                'updated_at' => '2025-05-18 10:41:55',
            ],
            [
                'id' => 21,
                'module_id' => 1,
                'title' => 'Python Module Index',
                'description' => 'Module index for Python',
                'source' => 'Python Docs',
                'type' => 'Documentation',
                'difficulty_level' => 'Beginner',
                'url' => 'https://docs.python.org/3/py-modindex.html',
                'order' => 3,
                'created_at' => '2025-05-18 10:43:38',
                'updated_at' => '2025-05-18 10:43:38',
            ],
        ]);

        // Seed migrations table
        DB::table('migrations')->insert([
            [
                'id' => 1,
                'migration' => '0000_00_01_110933_create_ranks_table',
                'batch' => 1,
            ],
            [
                'id' => 2,
                'migration' => '0001_01_01_000000_create_users_table',
                'batch' => 1,
            ],
            [
                'id' => 3,
                'migration' => '0001_01_01_000001_create_cache_table',
                'batch' => 1,
            ],
            [
                'id' => 4,
                'migration' => '0001_01_01_000002_create_jobs_table',
                'batch' => 1,
            ],
            [
                'id' => 5,
                'migration' => '2025_04_16_075557_create_personal_access_tokens_table',
                'batch' => 1,
            ],
            [
                'id' => 6,
                'migration' => '2025_04_17_092346_create_modules_table',
                'batch' => 1,
            ],
            [
                'id' => 7,
                'migration' => '2025_04_18_005122_create_courses_table',
                'batch' => 1,
            ],
            [
                'id' => 8,
                'migration' => '2025_05_14_040734_create_library_table',
                'batch' => 1,
            ],
            [
                'id' => 9,
                'migration' => '2025_05_14_195154_create_role_requests_table',
                'batch' => 1,
            ],
            [
                'id' => 10,
                'migration' => '2025_05_15_060038_create_achievements_table',
                'batch' => 1,
            ],
            [
                'id' => 11,
                'migration' => '2025_05_15_091541_create_user_achievements_table',
                'batch' => 1,
            ],
            [
                'id' => 12,
                'migration' => '2025_05_16_072000_create_quizzes_table',
                'batch' => 1,
            ],
            [
                'id' => 13,
                'migration' => '2025_05_16_073117_create_questions_table',
                'batch' => 1,
            ],
            [
                'id' => 14,
                'migration' => '2025_05_16_073303_create_answers_table',
                'batch' => 1,
            ],
            [
                'id' => 15,
                'migration' => '2025_05_16_073757_create_quiz_attempts_table',
                'batch' => 1,
            ],
            [
                'id' => 16,
                'migration' => '2025_05_16_074105_create_quiz_responses_table',
                'batch' => 1,
            ],
            [
                'id' => 17,
                'migration' => '2025_05_16_074509_create_affiliations_table',
                'batch' => 1,
            ],
            [
                'id' => 18,
                'migration' => '2025_05_21_113937_add_google_id_in_users',
                'batch' => 2,
            ],
        ]);

        // Seed questions table
        DB::table('questions')->insert([
            [
                'id' => 14,
                'quiz_id' => 2,
                'question_text' => 'What is the right way to print \"Hello World\" in Pythoon?',
                'created_at' => '2025-05-16 08:26:20',
                'updated_at' => '2025-05-16 08:26:20',
            ],
            [
                'id' => 15,
                'quiz_id' => 2,
                'question_text' => 'Blah Blah _____ Sheep',
                'created_at' => '2025-05-16 08:26:20',
                'updated_at' => '2025-05-16 08:26:20',
            ],
            [
                'id' => 16,
                'quiz_id' => 2,
                'question_text' => '_ython',
                'created_at' => '2025-05-16 08:26:20',
                'updated_at' => '2025-05-16 08:26:20',
            ],
            [
                'id' => 17,
                'quiz_id' => 2,
                'question_text' => 'Another Question?',
                'created_at' => '2025-05-16 08:26:20',
                'updated_at' => '2025-05-16 08:26:20',
            ],
            [
                'id' => 19,
                'quiz_id' => 4,
                'question_text' => 'Question Template',
                'created_at' => '2025-05-18 12:16:13',
                'updated_at' => '2025-05-18 12:16:13',
            ],
            [
                'id' => 20,
                'quiz_id' => 4,
                'question_text' => 'Question Template 2',
                'created_at' => '2025-05-18 12:16:13',
                'updated_at' => '2025-05-18 12:16:13',
            ],
            [
                'id' => 21,
                'quiz_id' => 4,
                'question_text' => 'Question Template 3',
                'created_at' => '2025-05-18 12:16:13',
                'updated_at' => '2025-05-18 12:16:13',
            ],
        ]);

        // Seed answers table
        DB::table('answers')->insert([
            [
                'id' => 49,
                'question_id' => 14,
                'answer_text' => 'print \"Hello World\"',
                'is_correct' => 0,
                'created_at' => '2025-05-16 08:26:20',
                'updated_at' => '2025-05-16 08:26:20',
            ],
            [
                'id' => 50,
                'question_id' => 14,
                'answer_text' => 'print (Hello World)',
                'is_correct' => 0,
                'created_at' => '2025-05-16 08:26:20',
                'updated_at' => '2025-05-16 08:26:20',
            ],
            [
                'id' => 51,
                'question_id' => 14,
                'answer_text' => 'print (\"Hello World\")',
                'is_correct' => 1,
                'created_at' => '2025-05-16 08:26:20',
                'updated_at' => '2025-05-16 08:26:20',
            ],
            [
                'id' => 52,
                'question_id' => 14,
                'answer_text' => 'system.out.println(\"Hello World\")',
                'is_correct' => 0,
                'created_at' => '2025-05-16 08:26:20',
                'updated_at' => '2025-05-16 08:26:20',
            ],
            [
                'id' => 53,
                'question_id' => 15,
                'answer_text' => 'White',
                'is_correct' => 0,
                'created_at' => '2025-05-16 08:26:20',
                'updated_at' => '2025-05-16 08:26:20',
            ],
            [
                'id' => 54,
                'question_id' => 15,
                'answer_text' => 'Pink',
                'is_correct' => 0,
                'created_at' => '2025-05-16 08:26:20',
                'updated_at' => '2025-05-16 08:26:20',
            ],
            [
                'id' => 55,
                'question_id' => 15,
                'answer_text' => 'Black',
                'is_correct' => 1,
                'created_at' => '2025-05-16 08:26:20',
                'updated_at' => '2025-05-16 08:26:20',
            ],
            [
                'id' => 56,
                'question_id' => 15,
                'answer_text' => 'Red',
                'is_correct' => 0,
                'created_at' => '2025-05-16 08:26:20',
                'updated_at' => '2025-05-16 08:26:20',
            ],
            [
                'id' => 57,
                'question_id' => 16,
                'answer_text' => 'B',
                'is_correct' => 0,
                'created_at' => '2025-05-16 08:26:20',
                'updated_at' => '2025-05-16 08:26:20',
            ],
            [
                'id' => 58,
                'question_id' => 16,
                'answer_text' => 'S',
                'is_correct' => 0,
                'created_at' => '2025-05-16 08:26:20',
                'updated_at' => '2025-05-16 08:26:20',
            ],
            [
                'id' => 59,
                'question_id' => 16,
                'answer_text' => 'P',
                'is_correct' => 1,
                'created_at' => '2025-05-16 08:26:20',
                'updated_at' => '2025-05-16 08:26:20',
            ],
            [
                'id' => 60,
                'question_id' => 16,
                'answer_text' => 'W',
                'is_correct' => 0,
                'created_at' => '2025-05-16 08:26:20',
                'updated_at' => '2025-05-16 08:26:20',
            ],
            [
                'id' => 61,
                'question_id' => 17,
                'answer_text' => '...',
                'is_correct' => 0,
                'created_at' => '2025-05-16 08:26:20',
                'updated_at' => '2025-05-16 08:26:20',
            ],
            [
                'id' => 62,
                'question_id' => 17,
                'answer_text' => '....',
                'is_correct' => 0,
                'created_at' => '2025-05-16 08:26:20',
                'updated_at' => '2025-05-16 08:26:20',
            ],
            [
                'id' => 63,
                'question_id' => 17,
                'answer_text' => '.....',
                'is_correct' => 0,
                'created_at' => '2025-05-16 08:26:20',
                'updated_at' => '2025-05-16 08:26:20',
            ],
            [
                'id' => 64,
                'question_id' => 17,
                'answer_text' => '......',
                'is_correct' => 1,
                'is_correct' => 0,
                'created_at' => '2025-05-16 08:26:20',
                'updated_at' => '2025-05-16 08:26:20',
            ],
            [
                'id' => 69,
                'question_id' => 19,
                'answer_text' => 'Answer Template 1',
                'is_correct' => 0,
                'created_at' => '2025-05-18 12:16:13',
                'updated_at' => '2025-05-18 12:16:13',
            ],
            [
                'id' => 70,
                'question_id' => 19,
                'answer_text' => 'Answer Template 2',
                'is_correct' => 0,
                'created_at' => '2025-05-18 12:16:13',
                'updated_at' => '2025-05-18 12:16:13',
            ],
            [
                'id' => 71,
                'question_id' => 19,
                'answer_text' => 'Answer Template 3',
                'is_correct' => 0,
                'created_at' => '2025-05-18 12:16:13',
                'updated_at' => '2025-05-18 12:16:13',
            ],
            [
                'id' => 72,
                'question_id' => 19,
                'answer_text' => 'Answer Template 4',
                'is_correct' => 1,
                'created_at' => '2025-05-18 12:16:13',
                'updated_at' => '2025-05-18 12:16:13',
            ],
            [
                'id' => 73,
                'question_id' => 20,
                'answer_text' => 'Answer Template 1',
                'is_correct' => 1,
                'created_at' => '2025-05-18 12:16:13',
                'updated_at' => '2025-05-18 12:16:13',
            ],
            [
                'id' => 74,
                'question_id' => 20,
                'answer_text' => 'Answer Template 2',
                'is_correct' => 0,
                'created_at' => '2025-05-18 12:16:13',
                'updated_at' => '2025-05-18 12:16:13',
            ],
            [
                'id' => 75,
                'question_id' => 20,
                'answer_text' => 'Answer Template 3',
                'is_correct' => 0,
                'created_at' => '2025-05-18 12:16:13',
                'updated_at' => '2025-05-18 12:16:13',
            ],
            [
                'id' => 76,
                'question_id' => 20,
                'answer_text' => 'Answer Template 4',
                'is_correct' => 0,
                'created_at' => '2025-05-18 12:16:13',
                'updated_at' => '2025-05-18 12:16:13',
            ],
            [
                'id' => 77,
                'question_id' => 21,
                'answer_text' => 'Answer Template 1',
                'is_correct' => 0,
                'created_at' => '2025-05-18 12:16:13',
                'updated_at' => '2025-05-18 12:16:13',
            ],
            [
                'id' => 78,
                'question_id' => 21,
                'answer_text' => 'Answer Template 2',
                'is_correct' => 1,
                'created_at' => '2025-05-18 12:16:13',
                'updated_at' => '2025-05-18 12:16:13',
            ],
            [
                'id' => 79,
                'question_id' => 21,
                'answer_text' => 'Answer Template 3',
                'is_correct' => 0,
                'created_at' => '2025-05-18 12:16:13',
                'updated_at' => '2025-05-18 12:16:13',
            ],
            [
                'id' => 80,
                'question_id' => 21,
                'answer_text' => 'Answer Template 4',
                'is_correct' => 0,
                'created_at' => '2025-05-18 12:16:13',
                'updated_at' => '2025-05-18 12:16:13',
            ],
        ]);

        // Seed quiz_responses table
        DB::table('quiz_responses')->insert([
            [
                'id' => 5,
                'quiz_attempt_id' => 2,
                'question_id' => 19,
                'answer_id' => 72,
                'created_at' => '2025-05-18 12:25:56',
                'updated_at' => '2025-05-18 12:25:56',
            ],
            [
                'id' => 6,
                'quiz_attempt_id' => 2,
                'question_id' => 20,
                'answer_id' => 73,
                'created_at' => '2025-05-18 12:25:56',
                'updated_at' => '2025-05-18 12:25:56',
            ],
            [
                'id' => 7,
                'quiz_attempt_id' => 2,
                'question_id' => 21,
                'answer_id' => 78,
                'created_at' => '2025-05-18 12:25:56',
                'updated_at' => '2025-05-18 12:25:56',
            ],
        ]);
        

        // Seed users table - Default Admin
        DB::table('users')->insert([
            [
                'name' => 'Admin',
                'email' => 'admin@gmail.com',
                'password' => bcrypt('admin123'),
                'role' => 'Admin',
                'profile_image' => 'uploads/admin.png',
                'rank_id' => 1,
                'created_at' => now(),
                'updated_at' => now()
            ]
        ]);
    }
}
